DETECTOR_MODEL = "precompiled_models/shape_predictor_68_face_landmarks.dat"
FACE_IMAGE_SIZE = 500

LOWEST_CHIN_POINT_INDEX = 8
LEFT_EYEBROW_INNER_POINT_INDEX = 21
RIGTH_EYEBROW_INNER_POINT_INDEX = 22
LEFT_EAR = 1
RIGHT_EAR = 15
LEFT_CHIN_START = 5
RIGHT_CHIN_START = 11