DETECTOR_MODEL = "precompiled_models/shape_predictor_68_face_landmarks.dat"
FACE_IMAGE_SIZE = 1000

LOWEST_CHIN_POINT_INDEX = 8
HIGHTEST_CHIN_POINT_INDEX = 57

LEFT_EYEBROW_INNER_POINT_INDEX = 21
RIGTH_EYEBROW_INNER_POINT_INDEX = 22

LEFT_EYE_LEFTEST_POINT_INDEX = 36
LEFT_EYE_RIGHTEST_POINT_INDEX = 39
LEFT_EYE_LAST_POINT_INDEX = 41

RIGHT_EYE_RIGHTEST_POINT_INDEX = 45
RIGHT_EYE_LEFTEST_POINT_INDEX = 42
RIGHT_EYE_LAST_POINT_INDEX = 47


LEFT_EAR = 1
RIGHT_EAR = 15

LEFT_CHIN_START = 5
RIGHT_CHIN_START = 11