DETECTOR_MODEL = "precompiled_models/shape_predictor_68_face_landmarks.dat"
FACE_IMAGE_SIZE = 250

LOWEST_CHIN_POINT_INDEX = 8
HIGHTEST_CHIN_POINT_INDEX = 57

LEFT_EYEBROW_INNER_POINT_INDEX = 21
LEFT_EYEBROW_HEIGHEST_POINT_INDEX = 19
LEFT_EYEBROW_OUTER_POINT_INDEX = 17

RIGTH_EYEBROW_INNER_POINT_INDEX = 22
RIGHT_EYEBROW_HEIGHEST_POINT_INDEX = 24
RIGHT_EYEBROW_OUTER_POINT_INDEX = 26

LEFT_EYE_LEFTEST_POINT_INDEX = 36
LEFT_EYE_RIGHTEST_POINT_INDEX = 39
LEFT_EYE_LAST_POINT_INDEX = 41

RIGHT_EYE_RIGHTEST_POINT_INDEX = 45
RIGHT_EYE_LEFTEST_POINT_INDEX = 42
RIGHT_EYE_LAST_POINT_INDEX = 47


LEFT_EAR = 1
RIGHT_EAR = 15

LEFT_CHIN_START = 5
RIGHT_CHIN_START = 11

NOSE_LEFTEST_POINT_INDEX = 31
NOSE_RIGHTEST_POINT_INDEX = 35
NOSE_MIDDLE_POINT_INDEX = 33
NOSE_HEIGHTES_POINT_INDEX = 27

MOUTH_LOWEST_POINT_INDEX = 57
LOWER_LIP_END_POINT_INDEX = 66

MOUTH_HIGHEST_POINT_INDEX = 51
UPPER_LIP_END_POINT_INDEX = 62
MOUTH_LEFT_CORNER_INDEX = 48
MOUTH_RIGHT_CORNER_INDEX = 54